/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEvolutionProxyRouteImport } from './routes/api.evolution-proxy'
import { Route as ApiPublicWebhookRouteImport } from './routes/api.public.webhook'
import { Route as ApiEvolutionProxySplatRouteImport } from './routes/api.evolution-proxy.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionProxyRoute = ApiEvolutionProxyRouteImport.update({
  id: '/api/evolution-proxy',
  path: '/api/evolution-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionProxySplatRoute = ApiEvolutionProxySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiEvolutionProxyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/numbers': typeof NumbersRoute
  '/settings': typeof SettingsRoute
  '/api/evolution-proxy': typeof ApiEvolutionProxyRouteWithChildren
  '/api/evolution-proxy/$': typeof ApiEvolutionProxySplatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/numbers': typeof NumbersRoute
  '/settings': typeof SettingsRoute
  '/api/evolution-proxy': typeof ApiEvolutionProxyRouteWithChildren
  '/api/evolution-proxy/$': typeof ApiEvolutionProxySplatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/numbers': typeof NumbersRoute
  '/settings': typeof SettingsRoute
  '/api/evolution-proxy': typeof ApiEvolutionProxyRouteWithChildren
  '/api/evolution-proxy/$': typeof ApiEvolutionProxySplatRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/integracoes'
    | '/login'
    | '/numbers'
    | '/settings'
    | '/api/evolution-proxy'
    | '/api/evolution-proxy/$'
    | '/api/public/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/integracoes'
    | '/login'
    | '/numbers'
    | '/settings'
    | '/api/evolution-proxy'
    | '/api/evolution-proxy/$'
    | '/api/public/webhook'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/integracoes'
    | '/login'
    | '/numbers'
    | '/settings'
    | '/api/evolution-proxy'
    | '/api/evolution-proxy/$'
    | '/api/public/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AutomationsRoute: typeof AutomationsRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  NumbersRoute: typeof NumbersRoute
  SettingsRoute: typeof SettingsRoute
  ApiEvolutionProxyRoute: typeof ApiEvolutionProxyRouteWithChildren
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution-proxy': {
      id: '/api/evolution-proxy'
      path: '/api/evolution-proxy'
      fullPath: '/api/evolution-proxy'
      preLoaderRoute: typeof ApiEvolutionProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution-proxy/$': {
      id: '/api/evolution-proxy/$'
      path: '/$'
      fullPath: '/api/evolution-proxy/$'
      preLoaderRoute: typeof ApiEvolutionProxySplatRouteImport
      parentRoute: typeof ApiEvolutionProxyRoute
    }
  }
}

interface ApiEvolutionProxyRouteChildren {
  ApiEvolutionProxySplatRoute: typeof ApiEvolutionProxySplatRoute
}

const ApiEvolutionProxyRouteChildren: ApiEvolutionProxyRouteChildren = {
  ApiEvolutionProxySplatRoute: ApiEvolutionProxySplatRoute,
}

const ApiEvolutionProxyRouteWithChildren =
  ApiEvolutionProxyRoute._addFileChildren(ApiEvolutionProxyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AutomationsRoute: AutomationsRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  NumbersRoute: NumbersRoute,
  SettingsRoute: SettingsRoute,
  ApiEvolutionProxyRoute: ApiEvolutionProxyRouteWithChildren,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
